### ISSUE TITLE
Cannot clone repository

### ISSUE THREAD

**Issue by shaneargo** [blackboard/basic-b2-template#1]
When attempting to clone the repo I get a "Permission Denied" error:

---

git clone git@github.com:blackboard/basic-b2-template.git -o template projectname
Cloning into 'projectname'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.

---

I have had another user on another OS attempt, and they too had the issue.

**Comment by knightlabs** [comment]
You'll have to clone the project using http, not SSH: https://github.com/blackboard/basic-b2-template.git

**Comment by shaneargo** [comment]
Okay cool. 

You might want to consider updating the README.md then as this is where I was getting the instructions from.

**Comment by davidashman** [comment]
The README has been updated.  Thanks for letting us know.

dave

On August 20, 2013 at 5:50:23 AM, shaneargo (notifications@github.com) wrote:

Okay cool.

You might want to consider updating the README.md then as this is where I was getting the instructions from.
